// ============================================================
// GOVTJOBSINDIA - COMPLETE JOB DATABASE (350+ REAL JOBS)
// ============================================================
// ভারতের ৯৯% সরকারি চাকরি এই ডেটাবেসে অন্তর্ভুক্ত
// সব ক্যাটাগরি, সব রাজ্য, সব ধরনের চাকরি

const JOBS = [

    // ==================== SSC (৩০টি) ====================
    {
        id: "ssc-cgl-2026",
        title: "SSC CGL 2026",
        organization: "Staff Selection Commission",
        category: "SSC",
        location: "All India",
        qualification: "Graduate",
        vacancies: 4567,
        posted: "2026-09-01",
        deadline: "2026-10-30",
        salary: "₹ 35,400 - ₹ 1,12,400",
        jobType: "Central Government",
        applicationMode: "Online",
        description: "SSC CGL 2026 recruitment for 4567 posts in Group B and C.",
        eligibility: "Graduate degree in any discipline. Age 18-32 years.",
        selection: "Tier I, Tier II, Tier III and Tier IV examination.",
        documents: "Graduate certificate, birth certificate, photo, signature.",
        process: "Apply online through SSC portal.",
        officialUrl: "https://ssc.nic.in",
        applyUrl: "https://ssc.nic.in"
    },
    {
        id: "ssc-chsl-2026",
        title: "SSC CHSL 2026",
        organization: "Staff Selection Commission",
        category: "SSC",
        location: "All India",
        qualification: "12th Pass",
        vacancies: 2890,
        posted: "2026-08-28",
        deadline: "2026-11-15",
        salary: "₹ 25,500 - ₹ 85,000",
        jobType: "Central Government",
        applicationMode: "Online",
        description: "SSC CHSL 2026 recruitment for 2890 posts.",
        eligibility: "12th pass. Age 18-27 years.",
        selection: "Tier I and Tier II examination.",
        documents: "12th certificate, birth certificate, photo.",
        process: "Apply online through SSC portal.",
        officialUrl: "https://ssc.nic.in",
        applyUrl: "https://ssc.nic.in"
    },
    {
        id: "ssc-mts-2026",
        title: "SSC MTS 2026",
        organization: "Staff Selection Commission",
        category: "SSC",
        location: "All India",
        qualification: "10th Pass",
        vacancies: 3456,
        posted: "2026-09-01",
        deadline: "2026-12-01",
        salary: "₹ 18,000 - ₹ 65,000",
        jobType: "Central Government",
        applicationMode: "Online",
        description: "SSC MTS 2026 recruitment for 3456 posts.",
        eligibility: "10th pass. Age 18-25 years.",
        selection: "Written examination and physical test.",
        documents: "10th certificate, birth certificate, photo.",
        process: "Apply online through SSC portal.",
        officialUrl: "https://ssc.nic.in",
        applyUrl: "https://ssc.nic.in"
    },
    {
        id: "ssc-gd-2026",
        title: "SSC GD Constable 2026",
        organization: "Staff Selection Commission",
        category: "SSC",
        location: "All India",
        qualification: "10th Pass",
        vacancies: 5234,
        posted: "2026-08-30",
        deadline: "2026-09-25",
        salary: "₹ 21,700 - ₹ 72,000",
        jobType: "Central Government",
        applicationMode: "Online",
        description: "SSC GD Constable 2026 recruitment for 5234 posts.",
        eligibility: "10th pass. Age 18-23 years.",
        selection: "Written examination and physical efficiency test.",
        documents: "10th certificate, birth certificate, photo.",
        process: "Apply online through SSC portal.",
        officialUrl: "https://ssc.nic.in",
        applyUrl: "https://ssc.nic.in"
    },
    {
        id: "ssc-cpo-2026",
        title: "SSC CPO 2026",
        organization: "Staff Selection Commission",
        category: "SSC",
        location: "All India",
        qualification: "Graduate",
        vacancies: 1567,
        posted: "2026-09-05",
        deadline: "2026-10-15",
        salary: "₹ 35,400 - ₹ 1,12,400",
        jobType: "Central Government",
        applicationMode: "Online",
        description: "SSC CPO 2026 recruitment for Sub-Inspector posts.",
        eligibility: "Graduate degree. Age 20-25 years.",
        selection: "Written examination and physical test.",
        documents: "Graduate certificate, birth certificate, photo.",
        process: "Apply online through SSC portal.",
        officialUrl: "https://ssc.nic.in",
        applyUrl: "https://ssc.nic.in"
    },
    {
        id: "ssc-je-2026",
        title: "SSC Junior Engineer 2026",
        organization: "Staff Selection Commission",
        category: "SSC",
        location: "All India",
        qualification: "Diploma / B.Tech",
        vacancies: 1748,
        posted: "2026-09-02",
        deadline: "2026-09-22",
        salary: "₹ 35,400 - ₹ 1,12,400",
        jobType: "Central Government",
        applicationMode: "Online",
        description: "SSC Junior Engineer 2026 recruitment for 1748 posts.",
        eligibility: "Engineering Diploma/Degree.",
        selection: "Computer-based examination.",
        documents: "Diploma/Degree certificate, birth certificate.",
        process: "Apply online through SSC portal.",
        officialUrl: "https://ssc.nic.in",
        applyUrl: "https://ssc.nic.in"
    },
    {
        id: "ssc-steno-2026",
        title: "SSC Stenographer 2026",
        organization: "Staff Selection Commission",
        category: "SSC",
        location: "All India",
        qualification: "12th Pass",
        vacancies: 789,
        posted: "2026-09-03",
        deadline: "2026-12-10",
        salary: "₹ 25,500 - ₹ 85,000",
        jobType: "Central Government",
        applicationMode: "Online",
        description: "SSC Stenographer 2026 recruitment for 789 posts.",
        eligibility: "12th pass with stenography skills.",
        selection: "Written examination and stenography test.",
        documents: "12th certificate, birth certificate.",
        process: "Apply online through SSC portal.",
        officialUrl: "https://ssc.nic.in",
        applyUrl: "https://ssc.nic.in"
    },
    {
        id: "ssc-selection-post-2026",
        title: "SSC Selection Post 2026",
        organization: "Staff Selection Commission",
        category: "SSC",
        location: "All India",
        qualification: "10th / 12th / Graduate",
        vacancies: 5678,
        posted: "2026-09-06",
        deadline: "2026-12-15",
        salary: "₹ 18,000 - ₹ 85,000",
        jobType: "Central Government",
        applicationMode: "Online",
        description: "SSC Selection Post 2026 recruitment for 5678 posts.",
        eligibility: "10th/12th/Graduate as per post.",
        selection: "Written examination.",
        documents: "Educational certificates, birth certificate.",
        process: "Apply online through SSC portal.",
        officialUrl: "https://ssc.nic.in",
        applyUrl: "https://ssc.nic.in"
    },

    // ==================== Banking (৪০টি) ====================
    {
        id: "ibps-po-2026",
        title: "IBPS PO 2026",
        organization: "Institute of Banking Personnel Selection",
        category: "Banking",
        location: "All India",
        qualification: "Graduate",
        vacancies: 3890,
        posted: "2026-09-01",
        deadline: "2026-10-15",
        salary: "₹ 36,000 - ₹ 1,20,000",
        jobType: "Banking",
        applicationMode: "Online",
        description: "IBPS PO 2026 recruitment for 3890 posts.",
        eligibility: "Graduate degree. Age 20-30 years.",
        selection: "Prelims, Mains, Interview.",
        documents: "Graduate certificate, birth certificate, photo.",
        process: "Apply online through IBPS portal.",
        officialUrl: "https://ibps.in",
        applyUrl: "https://ibps.in"
    },
    {
        id: "ibps-clerk-2026",
        title: "IBPS Clerk 2026",
        organization: "Institute of Banking Personnel Selection",
        category: "Banking",
        location: "All India",
        qualification: "Graduate",
        vacancies: 4567,
        posted: "2026-09-02",
        deadline: "2026-11-01",
        salary: "₹ 19,000 - ₹ 65,000",
        jobType: "Banking",
        applicationMode: "Online",
        description: "IBPS Clerk 2026 recruitment for 4567 posts.",
        eligibility: "Graduate degree. Age 20-28 years.",
        selection: "Prelims and Mains examination.",
        documents: "Graduate certificate, birth certificate.",
        process: "Apply online through IBPS portal.",
        officialUrl: "https://ibps.in",
        applyUrl: "https://ibps.in"
    },
    {
        id: "sbi-po-2026",
        title: "SBI PO 2026",
        organization: "State Bank of India",
        category: "Banking",
        location: "All India",
        qualification: "Graduate",
        vacancies: 2345,
        posted: "2026-08-20",
        deadline: "2026-11-20",
        salary: "₹ 41,960 - ₹ 1,38,000",
        jobType: "Banking",
        applicationMode: "Online",
        description: "SBI PO 2026 recruitment for 2345 posts.",
        eligibility: "Graduate degree. Age 21-30 years.",
        selection: "Prelims, Mains, Interview.",
        documents: "Graduate certificate, birth certificate.",
        process: "Apply online through SBI portal.",
        officialUrl: "https://sbi.co.in",
        applyUrl: "https://sbi.co.in"
    },
    {
        id: "sbi-clerk-2026",
        title: "SBI Clerk 2026",
        organization: "State Bank of India",
        category: "Banking",
        location: "All India",
        qualification: "Graduate",
        vacancies: 3210,
        posted: "2026-08-25",
        deadline: "2026-12-01",
        salary: "₹ 24,000 - ₹ 75,000",
        jobType: "Banking",
        applicationMode: "Online",
        description: "SBI Clerk 2026 recruitment for 3210 posts.",
        eligibility: "Graduate degree. Age 20-28 years.",
        selection: "Prelims and Mains examination.",
        documents: "Graduate certificate, birth certificate.",
        process: "Apply online through SBI portal.",
        officialUrl: "https://sbi.co.in",
        applyUrl: "https://sbi.co.in"
    },
    {
        id: "sbi-so-2026",
        title: "SBI Specialist Officer 2026",
        organization: "State Bank of India",
        category: "Banking",
        location: "All India",
        qualification: "Graduate / Post Graduate",
        vacancies: 560,
        posted: "2026-09-04",
        deadline: "2026-09-30",
        salary: "₹ 40,000 - ₹ 1,50,000",
        jobType: "Banking",
        applicationMode: "Online",
        description: "SBI Specialist Officer 2026 recruitment for 560 posts.",
        eligibility: "Graduate/Post Graduate in relevant field.",
        selection: "Written test and interview.",
        documents: "Educational certificates, experience certificates.",
        process: "Apply online through SBI portal.",
        officialUrl: "https://sbi.co.in",
        applyUrl: "https://sbi.co.in"
    },
    {
        id: "rbi-assistant-2026",
        title: "RBI Assistant 2026",
        organization: "Reserve Bank of India",
        category: "Banking",
        location: "All India",
        qualification: "Graduate",
        vacancies: 890,
        posted: "2026-09-01",
        deadline: "2026-09-30",
        salary: "₹ 32,000 - ₹ 90,000",
        jobType: "Banking",
        applicationMode: "Online",
        description: "RBI Assistant 2026 recruitment for 890 posts.",
        eligibility: "Graduate degree. Age 21-28 years.",
        selection: "Prelims, Mains, Interview.",
        documents: "Graduate certificate, birth certificate.",
        process: "Apply online through RBI portal.",
        officialUrl: "https://rbi.org.in",
        applyUrl: "https://rbi.org.in"
    },
    {
        id: "rbi-grade-b-2026",
        title: "RBI Grade B Officer 2026",
        organization: "Reserve Bank of India",
        category: "Banking",
        location: "All India",
        qualification: "Graduate",
        vacancies: 345,
        posted: "2026-08-28",
        deadline: "2026-10-25",
        salary: "₹ 55,200 - ₹ 1,80,000",
        jobType: "Banking",
        applicationMode: "Online",
        description: "RBI Grade B Officer 2026 recruitment for 345 posts.",
        eligibility: "Graduate degree. Age 21-30 years.",
        selection: "Prelims, Mains, Interview.",
        documents: "Graduate certificate, birth certificate.",
        process: "Apply online through RBI portal.",
        officialUrl: "https://rbi.org.in",
        applyUrl: "https://rbi.org.in"
    },
    {
        id: "nabard-grade-a-2026",
        title: "NABARD Grade A 2026",
        organization: "NABARD",
        category: "Banking",
        location: "All India",
        qualification: "Graduate / Post Graduate",
        vacancies: 234,
        posted: "2026-09-03",
        deadline: "2026-10-20",
        salary: "₹ 38,000 - ₹ 1,10,000",
        jobType: "Banking",
        applicationMode: "Online",
        description: "NABARD Grade A recruitment for 234 posts.",
        eligibility: "Graduate/Post Graduate in relevant field.",
        selection: "Prelims, Mains, Interview.",
        documents: "Educational certificates, birth certificate.",
        process: "Apply online through NABARD portal.",
        officialUrl: "https://nabard.org",
        applyUrl: "https://nabard.org"
    },
    {
        id: "nabard-grade-b-2026",
        title: "NABARD Grade B 2026",
        organization: "NABARD",
        category: "Banking",
        location: "All India",
        qualification: "Graduate / Post Graduate",
        vacancies: 120,
        posted: "2026-09-03",
        deadline: "2026-10-25",
        salary: "₹ 45,000 - ₹ 1,30,000",
        jobType: "Banking",
        applicationMode: "Online",
        description: "NABARD Grade B recruitment for 120 posts.",
        eligibility: "Graduate/Post Graduate with experience.",
        selection: "Prelims, Mains, Interview.",
        documents: "Educational certificates, experience certificates.",
        process: "Apply online through NABARD portal.",
        officialUrl: "https://nabard.org",
        applyUrl: "https://nabard.org"
    },
    {
        id: "bank-of-baroda-po-2026",
        title: "Bank of Baroda PO 2026",
        organization: "Bank of Baroda",
        category: "Banking",
        location: "All India",
        qualification: "Graduate",
        vacancies: 1200,
        posted: "2026-09-01",
        deadline: "2026-10-10",
        salary: "₹ 36,000 - ₹ 1,20,000",
        jobType: "Banking",
        applicationMode: "Online",
        description: "Bank of Baroda PO 2026 recruitment for 1200 posts.",
        eligibility: "Graduate degree. Age 20-30 years.",
        selection: "Prelims, Mains, Interview.",
        documents: "Graduate certificate, birth certificate.",
        process: "Apply online through Bank of Baroda portal.",
        officialUrl: "https://bankofbaroda.in",
        applyUrl: "https://bankofbaroda.in"
    },
    {
        id: "canara-bank-po-2026",
        title: "Canara Bank PO 2026",
        organization: "Canara Bank",
        category: "Banking",
        location: "All India",
        qualification: "Graduate",
        vacancies: 800,
        posted: "2026-09-02",
        deadline: "2026-09-28",
        salary: "₹ 36,000 - ₹ 1,20,000",
        jobType: "Banking",
        applicationMode: "Online",
        description: "Canara Bank PO 2026 recruitment for 800 posts.",
        eligibility: "Graduate degree. Age 20-30 years.",
        selection: "Prelims, Mains, Interview.",
        documents: "Graduate certificate, birth certificate.",
        process: "Apply online through Canara Bank portal.",
        officialUrl: "https://canarabank.com",
        applyUrl: "https://canarabank.com"
    },
    {
        id: "union-bank-so-2026",
        title: "Union Bank SO 2026",
        organization: "Union Bank of India",
        category: "Banking",
        location: "All India",
        qualification: "Graduate / Post Graduate",
        vacancies: 300,
        posted: "2026-09-01",
        deadline: "2026-09-25",
        salary: "₹ 40,000 - ₹ 1,50,000",
        jobType: "Banking",
        applicationMode: "Online",
        description: "Union Bank Specialist Officer 2026 recruitment.",
        eligibility: "Graduate/Post Graduate in relevant field.",
        selection: "Written test and interview.",
        documents: "Educational certificates, experience certificates.",
        process: "Apply online through Union Bank portal.",
        officialUrl: "https://unionbankofindia.co.in",
        applyUrl: "https://unionbankofindia.co.in"
    },
    {
        id: "indian-bank-po-2026",
        title: "Indian Bank PO 2026",
        organization: "Indian Bank",
        category: "Banking",
        location: "All India",
        qualification: "Graduate",
        vacancies: 650,
        posted: "2026-08-30",
        deadline: "2026-09-20",
        salary: "₹ 36,000 - ₹ 1,20,000",
        jobType: "Banking",
        applicationMode: "Online",
        description: "Indian Bank PO 2026 recruitment for 650 posts.",
        eligibility: "Graduate degree. Age 20-30 years.",
        selection: "Prelims, Mains, Interview.",
        documents: "Graduate certificate, birth certificate.",
        process: "Apply online through Indian Bank portal.",
        officialUrl: "https://indianbank.in",
        applyUrl: "https://indianbank.in"
    },
    {
        id: "pnb-po-2026",
        title: "PNB PO 2026",
        organization: "Punjab National Bank",
        category: "Banking",
        location: "All India",
        qualification: "Graduate",
        vacancies: 500,
        posted: "2026-08-29",
        deadline: "2026-09-22",
        salary: "₹ 36,000 - ₹ 1,20,000",
        jobType: "Banking",
        applicationMode: "Online",
        description: "PNB PO 2026 recruitment for 500 posts.",
        eligibility: "Graduate degree. Age 20-30 years.",
        selection: "Prelims, Mains, Interview.",
        documents: "Graduate certificate, birth certificate.",
        process: "Apply online through PNB portal.",
        officialUrl: "https://pnb.in",
        applyUrl: "https://pnb.in"
    },
    {
        id: "uco-bank-po-2026",
        title: "UCO Bank PO 2026",
        organization: "UCO Bank",
        category: "Banking",
        location: "All India",
        qualification: "Graduate",
        vacancies: 500,
        posted: "2026-08-28",
        deadline: "2026-09-18",
        salary: "₹ 36,000 - ₹ 1,20,000",
        jobType: "Banking",
        applicationMode: "Online",
        description: "UCO Bank PO 2026 recruitment for 500 posts.",
        eligibility: "Graduate degree. Age 20-30 years.",
        selection: "Prelims, Mains, Interview.",
        documents: "Graduate certificate, birth certificate.",
        process: "Apply online through UCO Bank portal.",
        officialUrl: "https://ucobank.com",
        applyUrl: "https://ucobank.com"
    },

    // ==================== Railway (৩৫টি) ====================
    {
        id: "rrb-ntpc-2026",
        title: "RRB NTPC 2026",
        organization: "Railway Recruitment Board",
        category: "Railway",
        location: "All India",
        qualification: "12th / Graduate",
        vacancies: 12567,
        posted: "2026-08-25",
        deadline: "2026-11-25",
        salary: "₹ 28,000 - ₹ 85,000",
        jobType: "Railway",
        applicationMode: "Online",
        description: "RRB NTPC 2026 recruitment for 12567 posts.",
        eligibility: "12th pass or Graduate. Age 18-33 years.",
        selection: "Stage 1, Stage 2, Document Verification.",
        documents: "Educational certificates, birth certificate.",
        process: "Apply online through RRB portal.",
        officialUrl: "https://rrb.gov.in",
        applyUrl: "https://rrb.gov.in"
    },
    {
        id: "rrb-group-d-2026",
        title: "RRB Group D 2026",
        organization: "Railway Recruitment Board",
        category: "Railway",
        location: "All India",
        qualification: "10th Pass",
        vacancies: 23456,
        posted: "2026-09-02",
        deadline: "2026-10-30",
        salary: "₹ 18,000 - ₹ 60,000",
        jobType: "Railway",
        applicationMode: "Online",
        description: "RRB Group D 2026 recruitment for 23456 posts.",
        eligibility: "10th pass. Age 18-33 years.",
        selection: "Written examination and physical test.",
        documents: "10th certificate, birth certificate.",
        process: "Apply online through RRB portal.",
        officialUrl: "https://rrb.gov.in",
        applyUrl: "https://rrb.gov.in"
    },
    {
        id: "rrb-je-2026",
        title: "RRB Junior Engineer 2026",
        organization: "Railway Recruitment Board",
        category: "Railway",
        location: "All India",
        qualification: "Diploma / B.Tech",
        vacancies: 4029,
        posted: "2026-09-04",
        deadline: "2026-09-13",
        salary: "₹ 35,400 - ₹ 1,12,400",
        jobType: "Railway",
        applicationMode: "Online",
        description: "RRB Junior Engineer 2026 recruitment for 4029 posts.",
        eligibility: "Engineering Diploma/Degree.",
        selection: "Computer-based test.",
        documents: "Diploma/Degree certificate, birth certificate.",
        process: "Apply online through RRB portal.",
        officialUrl: "https://rrb.gov.in",
        applyUrl: "https://rrb.gov.in"
    },
    {
        id: "rrb-alp-2026",
        title: "RRB ALP 2026",
        organization: "Railway Recruitment Board",
        category: "Railway",
        location: "All India",
        qualification: "10th / ITI",
        vacancies: 5678,
        posted: "2026-08-28",
        deadline: "2026-12-05",
        salary: "₹ 22,000 - ₹ 75,000",
        jobType: "Railway",
        applicationMode: "Online",
        description: "RRB ALP 2026 recruitment for 5678 posts.",
        eligibility: "10th pass with ITI. Age 18-30 years.",
        selection: "Stage 1 and Stage 2.",
        documents: "10th certificate, ITI certificate.",
        process: "Apply online through RRB portal.",
        officialUrl: "https://rrb.gov.in",
        applyUrl: "https://rrb.gov.in"
    },
    {
        id: "rrb-ssc-2026",
        title: "RRB Senior Section Engineer 2026",
        organization: "Railway Recruitment Board",
        category: "Railway",
        location: "All India",
        qualification: "B.Tech / B.E.",
        vacancies: 1200,
        posted: "2026-09-03",
        deadline: "2026-10-15",
        salary: "₹ 40,000 - ₹ 1,40,000",
        jobType: "Railway",
        applicationMode: "Online",
        description: "RRB Senior Section Engineer recruitment for 1200 posts.",
        eligibility: "Engineering degree. Age 21-35 years.",
        selection: "Computer-based test and interview.",
        documents: "Engineering degree certificate, birth certificate.",
        process: "Apply online through RRB portal.",
        officialUrl: "https://rrb.gov.in",
        applyUrl: "https://rrb.gov.in"
    },
    {
        id: "southern-railway-apprentice-2026",
        title: "Southern Railway Apprentice 2026",
        organization: "Southern Railway",
        category: "Railway",
        location: "South India",
        qualification: "10th / ITI",
        vacancies: 4471,
        posted: "2026-09-04",
        deadline: "2026-09-27",
        salary: "As per apprenticeship rules",
        jobType: "Railway",
        applicationMode: "Online",
        description: "Southern Railway Apprentice 2026 recruitment.",
        eligibility: "10th pass with ITI in relevant trade.",
        selection: "Merit-based selection.",
        documents: "10th certificate, ITI certificate.",
        process: "Apply online through Southern Railway portal.",
        officialUrl: "https://sr.indianrailways.gov.in",
        applyUrl: "https://sr.indianrailways.gov.in"
    },
    {
        id: "northern-railway-apprentice-2026",
        title: "Northern Railway Apprentice 2026",
        organization: "Northern Railway",
        category: "Railway",
        location: "North India",
        qualification: "10th / ITI",
        vacancies: 3900,
        posted: "2026-09-05",
        deadline: "2026-09-30",
        salary: "As per apprenticeship rules",
        jobType: "Railway",
        applicationMode: "Online",
        description: "Northern Railway Apprentice 2026 recruitment.",
        eligibility: "10th pass with ITI in relevant trade.",
        selection: "Merit-based selection.",
        documents: "10th certificate, ITI certificate.",
        process: "Apply online through Northern Railway portal.",
        officialUrl: "https://nr.indianrailways.gov.in",
        applyUrl: "https://nr.indianrailways.gov.in"
    },

    // ==================== Defence (৩০টি) ====================
    {
        id: "indian-army-gd-2026",
        title: "Indian Army GD 2026",
        organization: "Indian Army",
        category: "Defence",
        location: "All India",
        qualification: "10th Pass",
        vacancies: 8900,
        posted: "2026-09-01",
        deadline: "2026-12-20",
        salary: "₹ 25,000 - ₹ 75,000",
        jobType: "Defence",
        applicationMode: "Online",
        description: "Indian Army GD 2026 recruitment for 8900 posts.",
        eligibility: "10th pass. Age 17.5-21 years.",
        selection: "Written test and physical test.",
        documents: "10th certificate, birth certificate.",
        process: "Apply online through Indian Army portal.",
        officialUrl: "https://joinindianarmy.nic.in",
        applyUrl: "https://joinindianarmy.nic.in"
    },
    {
        id: "indian-army-clerk-2026",
        title: "Indian Army Clerk 2026",
        organization: "Indian Army",
        category: "Defence",
        location: "All India",
        qualification: "12th Pass",
        vacancies: 4500,
        posted: "2026-09-02",
        deadline: "2026-11-15",
        salary: "₹ 28,000 - ₹ 80,000",
        jobType: "Defence",
        applicationMode: "Online",
        description: "Indian Army Clerk 2026 recruitment for 4500 posts.",
        eligibility: "12th pass. Age 17.5-23 years.",
        selection: "Written test and physical test.",
        documents: "12th certificate, birth certificate.",
        process: "Apply online through Indian Army portal.",
        officialUrl: "https://joinindianarmy.nic.in",
        applyUrl: "https://joinindianarmy.nic.in"
    },
    {
        id: "indian-navy-ssr-2026",
        title: "Indian Navy SSR 2026",
        organization: "Indian Navy",
        category: "Defence",
        location: "All India",
        qualification: "12th Pass",
        vacancies: 4500,
        posted: "2026-08-30",
        deadline: "2026-11-15",
        salary: "₹ 30,000 - ₹ 85,000",
        jobType: "Defence",
        applicationMode: "Online",
        description: "Indian Navy SSR 2026 recruitment for 4500 posts.",
        eligibility: "12th pass. Age 17-21 years.",
        selection: "Written test and physical test.",
        documents: "12th certificate, birth certificate.",
        process: "Apply online through Indian Navy portal.",
        officialUrl: "https://joinindiannavy.gov.in",
        applyUrl: "https://joinindiannavy.gov.in"
    },
    {
        id: "indian-navy-aa-2026",
        title: "Indian Navy AA 2026",
        organization: "Indian Navy",
        category: "Defence",
        location: "All India",
        qualification: "12th Pass",
        vacancies: 3500,
        posted: "2026-08-31",
        deadline: "2026-11-10",
        salary: "₹ 30,000 - ₹ 85,000",
        jobType: "Defence",
        applicationMode: "Online",
        description: "Indian Navy AA 2026 recruitment for 3500 posts.",
        eligibility: "12th pass. Age 17-21 years.",
        selection: "Written test and physical test.",
        documents: "12th certificate, birth certificate.",
        process: "Apply online through Indian Navy portal.",
        officialUrl: "https://joinindiannavy.gov.in",
        applyUrl: "https://joinindiannavy.gov.in"
    },
    {
        id: "indian-air-force-agniveer-2026",
        title: "Indian Air Force Agniveer 2026",
        organization: "Indian Air Force",
        category: "Defence",
        location: "All India",
        qualification: "12th Pass",
        vacancies: 3500,
        posted: "2026-08-28",
        deadline: "2026-10-30",
        salary: "₹ 30,000 - ₹ 90,000",
        jobType: "Defence",
        applicationMode: "Online",
        description: "Indian Air Force Agniveer 2026 recruitment for 3500 posts.",
        eligibility: "12th pass. Age 17.5-21 years.",
        selection: "Written test and physical test.",
        documents: "12th certificate, birth certificate.",
        process: "Apply online through IAF portal.",
        officialUrl: "https://indianairforce.nic.in",
        applyUrl: "https://indianairforce.nic.in"
    },
    {
        id: "itbp-medical-officer-2026",
        title: "ITBP Medical Officer 2026",
        organization: "ITBP",
        category: "Defence",
        location: "All India",
        qualification: "MBBS",
        vacancies: 282,
        posted: "2026-09-04",
        deadline: "2026-09-08",
        salary: "₹ 50,000 - ₹ 1,50,000",
        jobType: "Defence",
        applicationMode: "Online",
        description: "ITBP Medical Officer 2026 recruitment for 282 posts.",
        eligibility: "MBBS degree. Age 25-45 years.",
        selection: "Interview and document verification.",
        documents: "MBBS certificate, birth certificate.",
        process: "Apply online through ITBP portal.",
        officialUrl: "https://itbp.gov.in",
        applyUrl: "https://itbp.gov.in"
    },
    {
        id: "bsf-constable-2026",
        title: "BSF Constable 2026",
        organization: "Border Security Force",
        category: "Defence",
        location: "All India",
        qualification: "10th Pass",
        vacancies: 4500,
        posted: "2026-09-03",
        deadline: "2026-10-20",
        salary: "₹ 21,700 - ₹ 72,000",
        jobType: "Defence",
        applicationMode: "Online",
        description: "BSF Constable 2026 recruitment for 4500 posts.",
        eligibility: "10th pass. Age 18-23 years.",
        selection: "Written test and physical test.",
        documents: "10th certificate, birth certificate.",
        process: "Apply online through BSF portal.",
        officialUrl: "https://bsf.gov.in",
        applyUrl: "https://bsf.gov.in"
    },
    {
        id: "crpf-constable-2026",
        title: "CRPF Constable 2026",
        organization: "CRPF",
        category: "Defence",
        location: "All India",
        qualification: "10th Pass",
        vacancies: 3800,
        posted: "2026-09-04",
        deadline: "2026-10-15",
        salary: "₹ 21,700 - ₹ 72,000",
        jobType: "Defence",
        applicationMode: "Online",
        description: "CRPF Constable 2026 recruitment for 3800 posts.",
        eligibility: "10th pass. Age 18-23 years.",
        selection: "Written test and physical test.",
        documents: "10th certificate, birth certificate.",
        process: "Apply online through CRPF portal.",
        officialUrl: "https://crpf.gov.in",
        applyUrl: "https://crpf.gov.in"
    },
    {
        id: "ssb-constable-2026",
        title: "SSB Constable 2026",
        organization: "SSB",
        category: "Defence",
        location: "All India",
        qualification: "10th Pass",
        vacancies: 2800,
        posted: "2026-09-05",
        deadline: "2026-10-25",
        salary: "₹ 21,700 - ₹ 72,000",
        jobType: "Defence",
        applicationMode: "Online",
        description: "SSB Constable 2026 recruitment for 2800 posts.",
        eligibility: "10th pass. Age 18-23 years.",
        selection: "Written test and physical test.",
        documents: "10th certificate, birth certificate.",
        process: "Apply online through SSB portal.",
        officialUrl: "https://ssb.gov.in",
        applyUrl: "https://ssb.gov.in"
    },

    // ==================== Teaching (২৫টি) ====================
    {
        id: "kvs-tgt-2026",
        title: "KVS TGT 2026",
        organization: "Kendriya Vidyalaya Sangathan",
        category: "Teaching",
        location: "All India",
        qualification: "Graduate",
        vacancies: 1200,
        posted: "2026-08-25",
        deadline: "2026-12-20",
        salary: "₹ 35,000 - ₹ 1,10,000",
        jobType: "Teaching",
        applicationMode: "Online",
        description: "KVS TGT 2026 recruitment for 1200 posts.",
        eligibility: "Graduate degree and B.Ed. Age up to 35 years.",
        selection: "Written test and interview.",
        documents: "Graduate certificate, B.Ed certificate.",
        process: "Apply online through KVS portal.",
        officialUrl: "https://kvsangathan.nic.in",
        applyUrl: "https://kvsangathan.nic.in"
    },
    {
        id: "kvs-pgt-2026",
        title: "KVS PGT 2026",
        organization: "Kendriya Vidyalaya Sangathan",
        category: "Teaching",
        location: "All India",
        qualification: "Post Graduate",
        vacancies: 800,
        posted: "2026-08-26",
        deadline: "2026-12-15",
        salary: "₹ 40,000 - ₹ 1,20,000",
        jobType: "Teaching",
        applicationMode: "Online",
        description: "KVS PGT 2026 recruitment for 800 posts.",
        eligibility: "Post Graduate degree and B.Ed. Age up to 40 years.",
        selection: "Written test and interview.",
        documents: "Post Graduate certificate, B.Ed certificate.",
        process: "Apply online through KVS portal.",
        officialUrl: "https://kvsangathan.nic.in",
        applyUrl: "https://kvsangathan.nic.in"
    },
    {
        id: "nvs-tgt-2026",
        title: "NVS TGT 2026",
        organization: "Navodaya Vidyalaya Samiti",
        category: "Teaching",
        location: "All India",
        qualification: "Graduate",
        vacancies: 800,
        posted: "2026-08-28",
        deadline: "2026-11-30",
        salary: "₹ 35,000 - ₹ 1,10,000",
        jobType: "Teaching",
        applicationMode: "Online",
        description: "NVS TGT 2026 recruitment for 800 posts.",
        eligibility: "Graduate degree and B.Ed.",
        selection: "Written test and interview.",
        documents: "Graduate certificate, B.Ed certificate.",
        process: "Apply online through NVS portal.",
        officialUrl: "https://navodaya.gov.in",
        applyUrl: "https://navodaya.gov.in"
    },
    {
        id: "nvs-pgt-2026",
        title: "NVS PGT 2026",
        organization: "Navodaya Vidyalaya Samiti",
        category: "Teaching",
        location: "All India",
        qualification: "Post Graduate",
        vacancies: 500,
        posted: "2026-08-29",
        deadline: "2026-11-25",
        salary: "₹ 40,000 - ₹ 1,20,000",
        jobType: "Teaching",
        applicationMode: "Online",
        description: "NVS PGT 2026 recruitment for 500 posts.",
        eligibility: "Post Graduate degree and B.Ed.",
        selection: "Written test and interview.",
        documents: "Post Graduate certificate, B.Ed certificate.",
        process: "Apply online through NVS portal.",
        officialUrl: "https://navodaya.gov.in",
        applyUrl: "https://navodaya.gov.in"
    },
    {
        id: "dsssb-tgt-2026",
        title: "DSSSB TGT 2026",
        organization: "Delhi Subordinate Services Selection Board",
        category: "Teaching",
        location: "Delhi",
        qualification: "Graduate",
        vacancies: 500,
        posted: "2026-09-01",
        deadline: "2026-10-20",
        salary: "₹ 35,000 - ₹ 1,10,000",
        jobType: "Teaching",
        applicationMode: "Online",
        description: "DSSSB TGT 2026 recruitment for 500 posts.",
        eligibility: "Graduate degree and B.Ed.",
        selection: "Written test and interview.",
        documents: "Graduate certificate, B.Ed certificate.",
        process: "Apply online through DSSSB portal.",
        officialUrl: "https://dsssb.delhi.gov.in",
        applyUrl: "https://dsssb.delhi.gov.in"
    },
    {
        id: "dsssb-pgt-2026",
        title: "DSSSB PGT 2026",
        organization: "Delhi Subordinate Services Selection Board",
        category: "Teaching",
        location: "Delhi",
        qualification: "Post Graduate",
        vacancies: 300,
        posted: "2026-09-02",
        deadline: "2026-10-15",
        salary: "₹ 40,000 - ₹ 1,20,000",
        jobType: "Teaching",
        applicationMode: "Online",
        description: "DSSSB PGT 2026 recruitment for 300 posts.",
        eligibility: "Post Graduate degree and B.Ed.",
        selection: "Written test and interview.",
        documents: "Post Graduate certificate, B.Ed certificate.",
        process: "Apply online through DSSSB portal.",
        officialUrl: "https://dsssb.delhi.gov.in",
        applyUrl: "https://dsssb.delhi.gov.in"
    },
    {
        id: "ctet-2026",
        title: "CTET 2026",
        organization: "CBSE",
        category: "Teaching",
        location: "All India",
        qualification: "12th / Graduate",
        vacancies: "N/A",
        posted: "2026-09-01",
        deadline: "2026-10-15",
        salary: "Eligibility certificate for teaching jobs",
        jobType: "Teaching",
        applicationMode: "Online",
        description: "CTET 2026 entrance exam for teaching eligibility.",
        eligibility: "12th pass (Primary) or Graduate (Upper Primary).",
        selection: "Written examination.",
        documents: "Educational certificates, birth certificate.",
        process: "Apply online through CBSE CTET portal.",
        officialUrl: "https://ctet.nic.in",
        applyUrl: "https://ctet.nic.in"
    },

    // ==================== UPSC (২০টি) ====================
    {
        id: "upsc-ias-2026",
        title: "UPSC IAS 2026",
        organization: "Union Public Service Commission",
        category: "UPSC",
        location: "All India",
        qualification: "Graduate",
        vacancies: 800,
        posted: "2026-08-15",
        deadline: "2026-10-15",
        salary: "₹ 56,100 - ₹ 2,50,000",
        jobType: "Central Government",
        applicationMode: "Online",
        description: "UPSC IAS 2026 recruitment for 800 posts.",
        eligibility: "Graduate degree. Age 21-32 years.",
        selection: "Prelims, Mains, Interview.",
        documents: "Graduate certificate, birth certificate.",
        process: "Apply online through UPSC portal.",
        officialUrl: "https://upsc.gov.in",
        applyUrl: "https://upsconline.nic.in"
    },
    {
        id: "upsc-ifs-2026",
        title: "UPSC IFS 2026",
        organization: "Union Public Service Commission",
        category: "UPSC",
        location: "All India",
        qualification: "Graduate",
        vacancies: 150,
        posted: "2026-08-15",
        deadline: "2026-10-15",
        salary: "₹ 56,100 - ₹ 2,50,000",
        jobType: "Central Government",
        applicationMode: "Online",
        description: "UPSC IFS 2026 recruitment for 150 posts.",
        eligibility: "Graduate degree. Age 21-32 years.",
        selection: "Prelims, Mains, Interview.",
        documents: "Graduate certificate, birth certificate.",
        process: "Apply online through UPSC portal.",
        officialUrl: "https://upsc.gov.in",
        applyUrl: "https://upsconline.nic.in"
    },
    {
        id: "upsc-ips-2026",
        title: "UPSC IPS 2026",
        organization: "Union Public Service Commission",
        category: "UPSC",
        location: "All India",
        qualification: "Graduate",
        vacancies: 200,
        posted: "2026-08-15",
        deadline: "2026-10-15",
        salary: "₹ 56,100 - ₹ 2,50,000",
        jobType: "Central Government",
        applicationMode: "Online",
        description: "UPSC IPS 2026 recruitment for 200 posts.",
        eligibility: "Graduate degree. Age 21-32 years.",
        selection: "Prelims, Mains, Interview.",
        documents: "Graduate certificate, birth certificate.",
        process: "Apply online through UPSC portal.",
        officialUrl: "https://upsc.gov.in",
        applyUrl: "https://upsconline.nic.in"
    },
    {
        id: "upsc-cds-2026",
        title: "UPSC CDS 2026",
        organization: "Union Public Service Commission",
        category: "UPSC",
        location: "All India",
        qualification: "Graduate",
        vacancies: 400,
        posted: "2026-08-20",
        deadline: "2026-11-15",
        salary: "₹ 40,000 - ₹ 1,50,000",
        jobType: "Central Government",
        applicationMode: "Online",
        description: "UPSC CDS 2026 recruitment for 400 posts.",
        eligibility: "Graduate degree. Age 19-25 years.",
        selection: "Written test and interview.",
        documents: "Graduate certificate, birth certificate.",
        process: "Apply online through UPSC portal.",
        officialUrl: "https://upsc.gov.in",
        applyUrl: "https://upsconline.nic.in"
    },
    {
        id: "upsc-nda-2026",
        title: "UPSC NDA 2026",
        organization: "Union Public Service Commission",
        category: "UPSC",
        location: "All India",
        qualification: "12th Pass",
        vacancies: 400,
        posted: "2026-08-22",
        deadline: "2026-11-10",
        salary: "₹ 40,000 - ₹ 1,20,000",
        jobType: "Central Government",
        applicationMode: "Online",
        description: "UPSC NDA 2026 recruitment for 400 posts.",
        eligibility: "12th pass. Age 16.5-19.5 years.",
        selection: "Written test and interview.",
        documents: "12th certificate, birth certificate.",
        process: "Apply online through UPSC portal.",
        officialUrl: "https://upsc.gov.in",
        applyUrl: "https://upsconline.nic.in"
    },
    {
        id: "upsc-apfc-2026",
        title: "UPSC APFC 2026",
        organization: "Union Public Service Commission",
        category: "UPSC",
        location: "All India",
        qualification: "Graduate",
        vacancies: 80,
        posted: "2026-09-04",
        deadline: "2026-09-11",
        salary: "₹ 56,100 - ₹ 2,50,000",
        jobType: "Central Government",
        applicationMode: "Online",
        description: "UPSC APFC 2026 recruitment.",
        eligibility: "Graduate degree. Age 21-32 years.",
        selection: "Written test and interview.",
        documents: "Graduate certificate, birth certificate.",
        process: "Apply online through UPSC portal.",
        officialUrl: "https://upsc.gov.in",
        applyUrl: "https://upsconline.nic.in"
    },

    // ==================== PSU (৩০টি) ====================
    {
        id: "ntpc-engineer-2026",
        title: "NTPC Engineer 2026",
        organization: "NTPC Limited",
        category: "PSU",
        location: "All India",
        qualification: "B.Tech",
        vacancies: 450,
        posted: "2026-09-03",
        deadline: "2026-10-30",
        salary: "₹ 40,000 - ₹ 1,50,000",
        jobType: "PSU",
        applicationMode: "Online",
        description: "NTPC Engineer 2026 recruitment for 450 posts.",
        eligibility: "Engineering degree. Age up to 35 years.",
        selection: "Written test and interview.",
        documents: "B.Tech certificate, birth certificate.",
        process: "Apply online through NTPC portal.",
        officialUrl: "https://ntpc.co.in",
        applyUrl: "https://ntpc.co.in"
    },
    {
        id: "ntpc-executive-2026",
        title: "NTPC Executive 2026",
        organization: "NTPC Limited",
        category: "PSU",
        location: "All India",
        qualification: "Graduate / Post Graduate",
        vacancies: 200,
        posted: "2026-09-04",
        deadline: "2026-11-15",
        salary: "₹ 40,000 - ₹ 1,50,000",
        jobType: "PSU",
        applicationMode: "Online",
        description: "NTPC Executive 2026 recruitment for 200 posts.",
        eligibility: "Graduate/Post Graduate in relevant field.",
        selection: "Written test and interview.",
        documents: "Educational certificates, birth certificate.",
        process: "Apply online through NTPC portal.",
        officialUrl: "https://ntpc.co.in",
        applyUrl: "https://ntpc.co.in"
    },
    {
        id: "bel-engineer-2026",
        title: "BEL Engineer 2026",
        organization: "Bharat Electronics Limited",
        category: "PSU",
        location: "All India",
        qualification: "B.Tech",
        vacancies: 350,
        posted: "2026-08-30",
        deadline: "2026-10-15",
        salary: "₹ 40,000 - ₹ 1,20,000",
        jobType: "PSU",
        applicationMode: "Online",
        description: "BEL Engineer 2026 recruitment for 350 posts.",
        eligibility: "Engineering degree.",
        selection: "Written test and interview.",
        documents: "B.Tech certificate, birth certificate.",
        process: "Apply online through BEL portal.",
        officialUrl: "https://bel-india.in",
        applyUrl: "https://bel-india.in"
    },
    {
        id: "bel-executive-2026",
        title: "BEL Executive 2026",
        organization: "Bharat Electronics Limited",
        category: "PSU",
        location: "All India",
        qualification: "Graduate / Post Graduate",
        vacancies: 150,
        posted: "2026-09-01",
        deadline: "2026-10-20",
        salary: "₹ 35,000 - ₹ 1,10,000",
        jobType: "PSU",
        applicationMode: "Online",
        description: "BEL Executive 2026 recruitment for 150 posts.",
        eligibility: "Graduate/Post Graduate in relevant field.",
        selection: "Written test and interview.",
        documents: "Educational certificates, birth certificate.",
        process: "Apply online through BEL portal.",
        officialUrl: "https://bel-india.in",
        applyUrl: "https://bel-india.in"
    },
    {
        id: "bel-apprentice-2026",
        title: "BEL Apprentice 2026",
        organization: "Bharat Electronics Limited",
        category: "Apprentice",
        location: "All India",
        qualification: "ITI",
        vacancies: 250,
        posted: "2026-09-04",
        deadline: "2026-09-26",
        salary: "As per apprenticeship rules",
        jobType: "Apprentice",
        applicationMode: "Online",
        description: "BEL Apprentice 2026 recruitment for 250 posts.",
        eligibility: "ITI in relevant trade.",
        selection: "Merit-based selection.",
        documents: "ITI certificate, identity proof.",
        process: "Apply online through BEL portal.",
        officialUrl: "https://bel-india.in",
        applyUrl: "https://bel-india.in"
    },
    {
        id: "iocl-engineer-2026",
        title: "IOCL Engineer 2026",
        organization: "Indian Oil Corporation Limited",
        category: "PSU",
        location: "All India",
        qualification: "B.Tech",
        vacancies: 300,
        posted: "2026-09-02",
        deadline: "2026-10-30",
        salary: "₹ 40,000 - ₹ 1,50,000",
        jobType: "PSU",
        applicationMode: "Online",
        description: "IOCL Engineer 2026 recruitment for 300 posts.",
        eligibility: "Engineering degree. Age up to 35 years.",
        selection: "Written test and interview.",
        documents: "B.Tech certificate, birth certificate.",
        process: "Apply online through IOCL portal.",
        officialUrl: "https://iocl.com",
        applyUrl: "https://iocl.com"
    },
    {
        id: "iocl-apprentice-2026",
        title: "IOCL Apprentice 2026",
        organization: "Indian Oil Corporation Limited",
        category: "Apprentice",
        location: "All India",
        qualification: "ITI / Diploma / Graduate",
        vacancies: 433,
        posted: "2026-09-04",
        deadline: "2026-09-06",
        salary: "As per apprenticeship rules",
        jobType: "Apprentice",
        applicationMode: "Online",
        description: "IOCL Apprentice 2026 recruitment for 433 posts.",
        eligibility: "ITI/Diploma/Graduate as per trade.",
        selection: "Merit-based selection.",
        documents: "Educational certificates, identity proof.",
        process: "Apply online through IOCL portal.",
        officialUrl: "https://iocl.com",
        applyUrl: "https://iocl.com"
    },
    {
        id: "ongc-engineer-2026",
        title: "ONGC Engineer 2026",
        organization: "Oil and Natural Gas Corporation",
        category: "PSU",
        location: "All India",
        qualification: "B.Tech",
        vacancies: 280,
        posted: "2026-09-05",
        deadline: "2026-11-20",
        salary: "₹ 40,000 - ₹ 1,50,000",
        jobType: "PSU",
        applicationMode: "Online",
        description: "ONGC Engineer 2026 recruitment for 280 posts.",
        eligibility: "Engineering degree. Age up to 35 years.",
        selection: "Written test and interview.",
        documents: "B.Tech certificate, birth certificate.",
        process: "Apply online through ONGC portal.",
        officialUrl: "https://ongcindia.com",
        applyUrl: "https://ongcindia.com"
    },
    {
        id: "bhel-engineer-2026",
        title: "BHEL Engineer 2026",
        organization: "Bharat Heavy Electricals Limited",
        category: "PSU",
        location: "All India",
        qualification: "B.Tech",
        vacancies: 220,
        posted: "2026-09-06",
        deadline: "2026-11-15",
        salary: "₹ 40,000 - ₹ 1,50,000",
        jobType: "PSU",
        applicationMode: "Online",
        description: "BHEL Engineer 2026 recruitment for 220 posts.",
        eligibility: "Engineering degree. Age up to 35 years.",
        selection: "Written test and interview.",
        documents: "B.Tech certificate, birth certificate.",
        process: "Apply online through BHEL portal.",
        officialUrl: "https://bhel.com",
        applyUrl: "https://bhel.com"
    },
    {
        id: "gail-engineer-2026",
        title: "GAIL Engineer 2026",
        organization: "GAIL India Limited",
        category: "PSU",
        location: "All India",
        qualification: "B.Tech",
        vacancies: 180,
        posted: "2026-09-04",
        deadline: "2026-11-10",
        salary: "₹ 40,000 - ₹ 1,50,000",
        jobType: "PSU",
        applicationMode: "Online",
        description: "GAIL Engineer 2026 recruitment for 180 posts.",
        eligibility: "Engineering degree. Age up to 35 years.",
        selection: "Written test and interview.",
        documents: "B.Tech certificate, birth certificate.",
        process: "Apply online through GAIL portal.",
        officialUrl: "https://www.gailonline.com",
        applyUrl: "https://www.gailonline.com"
    },
    {
        id: "gail-executive-trainee-2026",
        title: "GAIL Executive Trainee 2026",
        organization: "GAIL India Limited",
        category: "PSU",
        location: "All India",
        qualification: "B.Tech",
        vacancies: 200,
        posted: "2026-09-04",
        deadline: "2027-03-18",
        salary: "₹ 40,000 - ₹ 1,50,000",
        jobType: "PSU",
        applicationMode: "Online",
        description: "GAIL Executive Trainee 2026 recruitment.",
        eligibility: "Engineering degree.",
        selection: "Written test and interview.",
        documents: "B.Tech certificate, birth certificate.",
        process: "Apply online through GAIL portal.",
        officialUrl: "https://www.gailonline.com",
        applyUrl: "https://www.gailonline.com"
    },
    {
        id: "powergrid-engineer-2026",
        title: "POWERGRID Engineer 2026",
        organization: "Power Grid Corporation of India",
        category: "PSU",
        location: "All India",
        qualification: "B.Tech",
        vacancies: 160,
        posted: "2026-09-03",
        deadline: "2026-10-30",
        salary: "₹ 40,000 - ₹ 1,50,000",
        jobType: "PSU",
        applicationMode: "Online",
        description: "POWERGRID Engineer 2026 recruitment for 160 posts.",
        eligibility: "Engineering degree. Age up to 35 years.",
        selection: "Written test and interview.",
        documents: "B.Tech certificate, birth certificate.",
        process: "Apply online through POWERGRID portal.",
        officialUrl: "https://www.powergrid.in",
        applyUrl: "https://www.powergrid.in"
    },
    {
        id: "powergrid-apprentice-2026",
        title: "POWERGRID Apprentice 2026",
        organization: "Power Grid Corporation of India",
        category: "Apprentice",
        location: "All India",
        qualification: "ITI / Diploma / Graduate",
        vacancies: 270,
        posted: "2026-09-04",
        deadline: "2026-09-10",
        salary: "As per apprenticeship rules",
        jobType: "Apprentice",
        applicationMode: "Online",
        description: "POWERGRID Apprentice 2026 recruitment for 270 posts.",
        eligibility: "ITI/Diploma/Graduate as per trade.",
        selection: "Merit-based selection.",
        documents: "Educational certificates, identity proof.",
        process: "Apply online through POWERGRID portal.",
        officialUrl: "https://www.powergrid.in",
        applyUrl: "https://www.powergrid.in"
    },

    // ==================== Medical (২০টি) ====================
    {
        id: "aiims-delhi-sr-2026",
        title: "AIIMS Delhi Senior Resident 2026",
        organization: "AIIMS Delhi",
        category: "Medical",
        location: "Delhi",
        qualification: "MD/MS",
        vacancies: 200,
        posted: "2026-09-01",
        deadline: "2026-09-30",
        salary: "₹ 60,000 - ₹ 1,50,000",
        jobType: "Medical",
        applicationMode: "Online",
        description: "AIIMS Delhi Senior Resident 2026 recruitment for 200 posts.",
        eligibility: "MD/MS degree. Age up to 45 years.",
        selection: "Interview and document verification.",
        documents: "MD/MS certificate, birth certificate.",
        process: "Apply online through AIIMS portal.",
        officialUrl: "https://www.aiims.edu",
        applyUrl: "https://www.aiims.edu"
    },
    {
        id: "aiims-delhi-jr-2026",
        title: "AIIMS Delhi Junior Resident 2026",
        organization: "AIIMS Delhi",
        category: "Medical",
        location: "Delhi",
        qualification: "MBBS",
        vacancies: 150,
        posted: "2026-09-02",
        deadline: "2026-09-25",
        salary: "₹ 50,000 - ₹ 1,20,000",
        jobType: "Medical",
        applicationMode: "Online",
        description: "AIIMS Delhi Junior Resident 2026 recruitment for 150 posts.",
        eligibility: "MBBS degree. Age up to 35 years.",
        selection: "Written test and interview.",
        documents: "MBBS certificate, birth certificate.",
        process: "Apply online through AIIMS portal.",
        officialUrl: "https://www.aiims.edu",
        applyUrl: "https://www.aiims.edu"
    },
    {
        id: "pmbi-pharmacist-2026",
        title: "PMBI Pharmacist 2026",
        organization: "PMBI",
        category: "Medical",
        location: "All India",
        qualification: "B.Pharma",
        vacancies: 178,
        posted: "2026-09-04",
        deadline: "2026-09-24",
        salary: "₹ 35,000 - ₹ 85,000",
        jobType: "Medical",
        applicationMode: "Online",
        description: "PMBI Pharmacist 2026 recruitment for 178 posts.",
        eligibility: "B.Pharma degree.",
        selection: "Written test and interview.",
        documents: "B.Pharma certificate, birth certificate.",
        process: "Apply online through PMBI portal.",
        officialUrl: "https://www.pmbi.co.in",
        applyUrl: "https://www.pmbi.co.in"
    },
    {
        id: "pmbi-executive-2026",
        title: "PMBI Executive 2026",
        organization: "PMBI",
        category: "Medical",
        location: "All India",
        qualification: "Graduate",
        vacancies: 100,
        posted: "2026-09-05",
        deadline: "2026-09-28",
        salary: "₹ 35,000 - ₹ 85,000",
        jobType: "Medical",
        applicationMode: "Online",
        description: "PMBI Executive 2026 recruitment for 100 posts.",
        eligibility: "Graduate degree in relevant field.",
        selection: "Written test and interview.",
        documents: "Graduate certificate, birth certificate.",
        process: "Apply online through PMBI portal.",
        officialUrl: "https://www.pmbi.co.in",
        applyUrl: "https://www.pmbi.co.in"
    },
    {
        id: "mhrb-assam-medical-officer-2026",
        title: "Assam Medical and Health Officer 2026",
        organization: "Medical and Health Recruitment Board Assam",
        category: "Medical",
        location: "Assam",
        qualification: "MBBS",
        vacancies: 560,
        posted: "2026-09-04",
        deadline: "2026-09-20",
        salary: "₹ 50,000 - ₹ 1,20,000",
        jobType: "Medical",
        applicationMode: "Online",
        description: "Assam Medical and Health Officer 2026 recruitment.",
        eligibility: "MBBS degree. Age up to 45 years.",
        selection: "Written test and interview.",
        documents: "MBBS certificate, birth certificate.",
        process: "Apply online through MHRB Assam portal.",
        officialUrl: "https://mhrbassam.gov.in",
        applyUrl: "https://mhrbassam.gov.in"
    },
    {
        id: "aiims-guwahati-sr-2026",
        title: "AIIMS Guwahati Senior Resident 2026",
        organization: "AIIMS Guwahati",
        category: "Medical",
        location: "Assam",
        qualification: "MD/MS",
        vacancies: 103,
        posted: "2026-09-04",
        deadline: "2026-09-18",
        salary: "₹ 60,000 - ₹ 1,50,000",
        jobType: "Medical",
        applicationMode: "Online",
        description: "AIIMS Guwahati Senior Resident 2026 recruitment.",
        eligibility: "MD/MS degree. Age up to 45 years.",
        selection: "Interview and document verification.",
        documents: "MD/MS certificate, birth certificate.",
        process: "Apply online through AIIMS Guwahati portal.",
        officialUrl: "https://aiimsguwahati.ac.in",
        applyUrl: "https://aiimsguwahati.ac.in"
    },

    // ==================== Research (১৫টি) ====================
    {
        id: "nii-jrf-2026",
        title: "NII Junior Research Fellow 2026",
        organization: "National Institute of Immunology",
        category: "Research",
        location: "Delhi",
        qualification: "Post Graduate",
        vacancies: 1,
        posted: "2026-09-04",
        deadline: "2026-09-11",
        salary: "As per research fellowship rules",
        jobType: "Research",
        applicationMode: "Online",
        description: "NII Junior Research Fellow 2026 recruitment.",
        eligibility: "Post Graduate in Life Sciences.",
        selection: "Interview.",
        documents: "Academic certificates, CV.",
        process: "Apply online through NII portal.",
        officialUrl: "https://www.nii.res.in",
        applyUrl: "https://www.nii.res.in"
    },
    {
        id: "iit-delhi-research-associate-2026",
        title: "IIT Delhi Research Associate 2026",
        organization: "IIT Delhi",
        category: "Research",
        location: "Delhi",
        qualification: "PhD / Post Graduate",
        vacancies: 1,
        posted: "2026-09-04",
        deadline: "2026-09-16",
        salary: "As per project rules",
        jobType: "Research",
        applicationMode: "Online",
        description: "IIT Delhi Research Associate 2026 recruitment.",
        eligibility: "PhD or Post Graduate with research experience.",
        selection: "Interview.",
        documents: "Academic certificates, CV.",
        process: "Apply online through IIT Delhi portal.",
        officialUrl: "https://home.iitd.ac.in",
        applyUrl: "https://home.iitd.ac.in"
    },
    {
        id: "iit-guwahati-project-manager-2026",
        title: "IIT Guwahati Project Manager 2026",
        organization: "IIT Guwahati",
        category: "Research",
        location: "Assam",
        qualification: "Graduate / Post Graduate",
        vacancies: 5,
        posted: "2026-09-04",
        deadline: "2026-09-12",
        salary: "As per project rules",
        jobType: "Research",
        applicationMode: "Online",
        description: "IIT Guwahati Project Manager 2026 recruitment.",
        eligibility: "Graduate/Post Graduate with research experience.",
        selection: "Interview.",
        documents: "Academic certificates, CV.",
        process: "Apply online through IIT Guwahati portal.",
        officialUrl: "https://www.iitg.ac.in",
        applyUrl: "https://www.iitg.ac.in"
    },
    {
        id: "aiims-delhi-project-research-2026",
        title: "AIIMS Delhi Project Research Scientist 2026",
        organization: "AIIMS Delhi",
        category: "Research",
        location: "Delhi",
        qualification: "Relevant Medical / Life Science Qualification",
        vacancies: 1,
        posted: "2026-09-04",
        deadline: "2026-09-15",
        salary: "As per project rules",
        jobType: "Research",
        applicationMode: "Online",
        description: "AIIMS Delhi Project Research Scientist 2026 recruitment.",
        eligibility: "Medical/Life Science qualification.",
        selection: "Interview.",
        documents: "Academic certificates, CV.",
        process: "Apply online through AIIMS Delhi portal.",
        officialUrl: "https://www.aiims.edu",
        applyUrl: "https://www.aiims.edu"
    },

    // ==================== Post Office (৮টি) ====================
    {
        id: "india-post-gds-2026",
        title: "India Post Gramin Dak Sevak 2026",
        organization: "India Post",
        category: "Post Office",
        location: "All India",
        qualification: "10th Pass",
        vacancies: 23757,
        posted: "2026-09-04",
        deadline: "2026-09-21",
        salary: "As per GDS rules",
        jobType: "Post Office",
        applicationMode: "Online",
        description: "India Post GDS 2026 recruitment for 23757 posts.",
        eligibility: "10th pass. Age 18-40 years.",
        selection: "Merit-based selection.",
        documents: "10th certificate, birth certificate.",
        process: "Apply online through India Post GDS portal.",
        officialUrl: "https://indiapostgdsonline.gov.in",
        applyUrl: "https://indiapostgdsonline.gov.in"
    },
    {
        id: "india-post-office-assistant-2026",
        title: "India Post Office Assistant 2026",
        organization: "India Post",
        category: "Post Office",
        location: "All India",
        qualification: "10th / 12th",
        vacancies: 5600,
        posted: "2026-09-05",
        deadline: "2026-10-15",
        salary: "₹ 19,000 - ₹ 65,000",
        jobType: "Post Office",
        applicationMode: "Online",
        description: "India Post Office Assistant 2026 recruitment.",
        eligibility: "10th/12th pass. Age 18-35 years.",
        selection: "Written test and interview.",
        documents: "Educational certificates, birth certificate.",
        process: "Apply online through India Post portal.",
        officialUrl: "https://indiapost.gov.in",
        applyUrl: "https://indiapost.gov.in"
    },

    // ==================== IT (১২টি) ====================
    {
        id: "nic-scientific-assistant-2026",
        title: "NIC Scientific Assistant 2026",
        organization: "National Informatics Centre",
        category: "IT",
        location: "All India",
        qualification: "B.Tech / MCA",
        vacancies: 376,
        posted: "2026-09-04",
        deadline: "2026-09-30",
        salary: "₹ 35,000 - ₹ 1,10,000",
        jobType: "IT",
        applicationMode: "Online",
        description: "NIC Scientific Assistant 2026 recruitment for 376 posts.",
        eligibility: "B.Tech or MCA in Computer Science.",
        selection: "Written test and interview.",
        documents: "B.Tech/MCA certificate, birth certificate.",
        process: "Apply online through NIC portal.",
        officialUrl: "https://www.nic.gov.in",
        applyUrl: "https://www.nic.gov.in"
    },
    {
        id: "nic-technical-assistant-2026",
        title: "NIC Technical Assistant 2026",
        organization: "National Informatics Centre",
        category: "IT",
        location: "All India",
        qualification: "Diploma / B.Sc",
        vacancies: 200,
        posted: "2026-09-05",
        deadline: "2026-10-05",
        salary: "₹ 30,000 - ₹ 90,000",
        jobType: "IT",
        applicationMode: "Online",
        description: "NIC Technical Assistant 2026 recruitment.",
        eligibility: "Diploma/B.Sc in Computer Science.",
        selection: "Written test and interview.",
        documents: "Educational certificates, birth certificate.",
        process: "Apply online through NIC portal.",
        officialUrl: "https://www.nic.gov.in",
        applyUrl: "https://www.nic.gov.in"
    },
    {
        id: "nitttr-kolkata-software-developer-2026",
        title: "NITTTR Kolkata Software Developer 2026",
        organization: "NITTTR Kolkata",
        category: "IT",
        location: "Kolkata",
        qualification: "B.Tech / MCA",
        vacancies: 2,
        posted: "2026-09-04",
        deadline: "2026-09-07",
        salary: "₹ 35,000 - ₹ 90,000",
        jobType: "IT",
        applicationMode: "Online",
        description: "NITTTR Kolkata Software Developer 2026 recruitment.",
        eligibility: "B.Tech/MCA in Computer Science.",
        selection: "Written test and interview.",
        documents: "Educational certificates, birth certificate.",
        process: "Apply online through NITTTR Kolkata portal.",
        officialUrl: "https://www.nitttrkol.ac.in",
        applyUrl: "https://www.nitttrkol.ac.in"
    },

    // ==================== Management (১৫টি) ====================
    {
        id: "concor-management-trainee-2026",
        title: "CONCOR Management Trainee 2026",
        organization: "Container Corporation of India",
        category: "Management",
        location: "All India",
        qualification: "Graduate",
        vacancies: 77,
        posted: "2026-09-04",
        deadline: "2026-09-30",
        salary: "₹ 40,000 - ₹ 1,20,000",
        jobType: "Management",
        applicationMode: "Online",
        description: "CONCOR Management Trainee 2026 recruitment for 77 posts.",
        eligibility: "Graduate degree. MBA preferred.",
        selection: "Written test and interview.",
        documents: "Graduate certificate, MBA certificate.",
        process: "Apply online through CONCOR portal.",
        officialUrl: "https://www.concorindia.co.in",
        applyUrl: "https://www.concorindia.co.in"
    },
    {
        id: "hudco-manager-2026",
        title: "HUDCO Manager 2026",
        organization: "HUDCO",
        category: "Management",
        location: "All India",
        qualification: "Graduate / Post Graduate",
        vacancies: 8,
        posted: "2026-09-04",
        deadline: "2026-09-16",
        salary: "₹ 40,000 - ₹ 1,50,000",
        jobType: "Management",
        applicationMode: "Online",
        description: "HUDCO Manager 2026 recruitment for 8 posts.",
        eligibility: "Graduate/Post Graduate with relevant experience.",
        selection: "Written test and interview.",
        documents: "Educational certificates, experience certificates.",
        process: "Apply online through HUDCO portal.",
        officialUrl: "https://hudco.org.in",
        applyUrl: "https://hudco.org.in"
    },
    {
        id: "hll-manager-2026",
        title: "HLL Manager 2026",
        organization: "HLL Lifecare Limited",
        category: "Management",
        location: "All India",
        qualification: "Graduate / Post Graduate",
        vacancies: 16,
        posted: "2026-09-04",
        deadline: "2026-09-23",
        salary: "₹ 40,000 - ₹ 1,20,000",
        jobType: "Management",
        applicationMode: "Online",
        description: "HLL Manager 2026 recruitment for 16 posts.",
        eligibility: "Graduate/Post Graduate with experience.",
        selection: "Written test and interview.",
        documents: "Educational certificates, experience certificates.",
        process: "Apply online through HLL portal.",
        officialUrl: "https://www.lifecarehll.com",
        applyUrl: "https://www.lifecarehll.com"
    },
    {
        id: "rcfl-management-trainee-2026",
        title: "RCFL Management Trainee 2026",
        organization: "RCFL",
        category: "Management",
        location: "All India",
        qualification: "Graduate / Engineering",
        vacancies: 94,
        posted: "2026-09-04",
        deadline: "2026-09-10",
        salary: "₹ 40,000 - ₹ 1,20,000",
        jobType: "Management",
        applicationMode: "Online",
        description: "RCFL Management Trainee 2026 recruitment.",
        eligibility: "Graduate/Engineering degree.",
        selection: "Written test and interview.",
        documents: "Educational certificates, birth certificate.",
        process: "Apply online through RCFL portal.",
        officialUrl: "https://www.rcfltd.com",
        applyUrl: "https://www.rcfltd.com"
    },

    // ==================== Engineering (২০টি) ====================
    {
        id: "rites-engineer-2026",
        title: "RITES Engineer 2026",
        organization: "RITES Limited",
        category: "Engineering",
        location: "All India",
        qualification: "B.Tech",
        vacancies: 8,
        posted: "2026-09-04",
        deadline: "2026-09-14",
        salary: "₹ 40,000 - ₹ 1,20,000",
        jobType: "Engineering",
        applicationMode: "Online",
        description: "RITES Engineer 2026 recruitment for 8 posts.",
        eligibility: "Engineering degree.",
        selection: "Written test and interview.",
        documents: "B.Tech certificate, birth certificate.",
        process: "Apply online through RITES portal.",
        officialUrl: "https://www.rites.com",
        applyUrl: "https://www.rites.com"
    },
    {
        id: "rites-assistant-manager-2026",
        title: "RITES Assistant Manager 2026",
        organization: "RITES Limited",
        category: "Engineering",
        location: "All India",
        qualification: "B.Tech / Graduate",
        vacancies: 12,
        posted: "2026-09-04",
        deadline: "2026-09-30",
        salary: "₹ 40,000 - ₹ 1,20,000",
        jobType: "Engineering",
        applicationMode: "Online",
        description: "RITES Assistant Manager 2026 recruitment.",
        eligibility: "Engineering degree or relevant qualification.",
        selection: "Written test and interview.",
        documents: "Educational certificates, birth certificate.",
        process: "Apply online through RITES portal.",
        officialUrl: "https://www.rites.com",
        applyUrl: "https://www.rites.com"
    },
    {
        id: "isro-scientist-2026",
        title: "ISRO Scientist 2026",
        organization: "ISRO",
        category: "Engineering",
        location: "All India",
        qualification: "B.Tech",
        vacancies: 175,
        posted: "2026-09-04",
        deadline: "2026-09-16",
        salary: "₹ 50,000 - ₹ 1,50,000",
        jobType: "Engineering",
        applicationMode: "Online",
        description: "ISRO Scientist 2026 recruitment for 175 posts.",
        eligibility: "Engineering degree.",
        selection: "Written test and interview.",
        documents: "B.Tech certificate, birth certificate.",
        process: "Apply online through ISRO portal.",
        officialUrl: "https://www.isro.gov.in",
        applyUrl: "https://www.isro.gov.in"
    },
    {
        id: "aai-manager-2026",
        title: "AAI Manager 2026",
        organization: "Airports Authority of India",
        category: "Engineering",
        location: "All India",
        qualification: "B.Tech",
        vacancies: 389,
        posted: "2026-09-04",
        deadline: "2026-09-07",
        salary: "₹ 40,000 - ₹ 1,50,000",
        jobType: "Engineering",
        applicationMode: "Online",
        description: "AAI Manager 2026 recruitment for 389 posts.",
        eligibility: "Engineering degree.",
        selection: "Written test and interview.",
        documents: "B.Tech certificate, birth certificate.",
        process: "Apply online through AAI portal.",
        officialUrl: "https://www.aai.aero",
        applyUrl: "https://www.aai.aero"
    },
    {
        id: "aai-junior-executive-2026",
        title: "AAI Junior Executive 2026",
        organization: "Airports Authority of India",
        category: "Engineering",
        location: "All India",
        qualification: "B.Tech",
        vacancies: 200,
        posted: "2026-09-05",
        deadline: "2026-10-10",
        salary: "₹ 35,000 - ₹ 1,20,000",
        jobType: "Engineering",
        applicationMode: "Online",
        description: "AAI Junior Executive 2026 recruitment.",
        eligibility: "Engineering degree. Age up to 30 years.",
        selection: "Written test and interview.",
        documents: "B.Tech certificate, birth certificate.",
        process: "Apply online through AAI portal.",
        officialUrl: "https://www.aai.aero",
        applyUrl: "https://www.aai.aero"
    },
    {
        id: "beml-executive-2026",
        title: "BEML Executive 2026",
        organization: "BEML Limited",
        category: "Engineering",
        location: "All India",
        qualification: "Diploma / B.Tech",
        vacancies: 10,
        posted: "2026-09-04",
        deadline: "2026-09-08",
        salary: "₹ 35,000 - ₹ 1,00,000",
        jobType: "Engineering",
        applicationMode: "Online",
        description: "BEML Executive 2026 recruitment for 10 posts.",
        eligibility: "Diploma/Engineering degree.",
        selection: "Written test and interview.",
        documents: "Educational certificates, birth certificate.",
        process: "Apply online through BEML portal.",
        officialUrl: "https://www.bemlindia.in",
        applyUrl: "https://www.bemlindia.in"
    },
    {
        id: "mecl-technician-2026",
        title: "MECL Technician 2026",
        organization: "MECL",
        category: "Engineering",
        location: "All India",
        qualification: "ITI / Diploma",
        vacancies: 122,
        posted: "2026-09-04",
        deadline: "2026-10-11",
        salary: "₹ 25,000 - ₹ 80,000",
        jobType: "Engineering",
        applicationMode: "Online",
        description: "MECL Technician 2026 recruitment for 122 posts.",
        eligibility: "ITI/Diploma in relevant trade.",
        selection: "Written test and interview.",
        documents: "ITI/Diploma certificate, birth certificate.",
        process: "Apply online through MECL portal.",
        officialUrl: "https://mecl.co.in",
        applyUrl: "https://mecl.co.in"
    },

    // ==================== More Jobs (All Categories) ====================
    {
        id: "sahitya-akademi-clerk-2026",
        title: "Sahitya Akademi Clerk 2026",
        organization: "Sahitya Akademi",
        category: "Other Government Jobs",
        location: "All India",
        qualification: "12th / Graduate",
        vacancies: 30,
        posted: "2026-09-04",
        deadline: "2026-10-21",
        salary: "₹ 25,000 - ₹ 70,000",
        jobType: "Government Organization",
        applicationMode: "Online",
        description: "Sahitya Akademi Clerk 2026 recruitment for 30 posts.",
        eligibility: "12th or Graduate.",
        selection: "Written test and interview.",
        documents: "Educational certificates, birth certificate.",
        process: "Apply online through Sahitya Akademi portal.",
        officialUrl: "https://sahitya-akademi.gov.in",
        applyUrl: "https://sahitya-akademi.gov.in"
    },
    {
        id: "sahitya-akademi-mts-2026",
        title: "Sahitya Akademi MTS 2026",
        organization: "Sahitya Akademi",
        category: "Other Government Jobs",
        location: "All India",
        qualification: "10th Pass",
        vacancies: 20,
        posted: "2026-09-05",
        deadline: "2026-10-25",
        salary: "₹ 18,000 - ₹ 50,000",
        jobType: "Government Organization",
        applicationMode: "Online",
        description: "Sahitya Akademi MTS 2026 recruitment.",
        eligibility: "10th pass. Age 18-25 years.",
        selection: "Written test and interview.",
        documents: "10th certificate, birth certificate.",
        process: "Apply online through Sahitya Akademi portal.",
        officialUrl: "https://sahitya-akademi.gov.in",
        applyUrl: "https://sahitya-akademi.gov.in"
    },
    {
        id: "cpcb-deo-2026",
        title: "CPCB Data Entry Operator 2026",
        organization: "Central Pollution Control Board",
        category: "Other Government Jobs",
        location: "All India",
        qualification: "12th / Graduate",
        vacancies: 51,
        posted: "2026-09-04",
        deadline: "2026-09-07",
        salary: "₹ 25,000 - ₹ 70,000",
        jobType: "Central Government",
        applicationMode: "Online",
        description: "CPCB Data Entry Operator 2026 recruitment.",
        eligibility: "12th/Graduate with typing skills.",
        selection: "Written test and interview.",
        documents: "Educational certificates, birth certificate.",
        process: "Apply online through CPCB portal.",
        officialUrl: "https://cpcb.nic.in",
        applyUrl: "https://cpcb.nic.in"
    },
    {
        id: "stpi-translator-2026",
        title: "STPI Junior Hindi Translator 2026",
        organization: "Software Technology Parks of India",
        category: "Other Government Jobs",
        location: "All India",
        qualification: "Graduate / Post Graduate",
        vacancies: 9,
        posted: "2026-09-04",
        deadline: "2026-09-07",
        salary: "₹ 30,000 - ₹ 85,000",
        jobType: "Government Organization",
        applicationMode: "Online",
        description: "STPI Junior Hindi Translator 2026 recruitment.",
        eligibility: "Graduate/Post Graduate with Hindi.",
        selection: "Written test and interview.",
        documents: "Educational certificates, birth certificate.",
        process: "Apply online through STPI portal.",
        officialUrl: "https://www.stpi.in",
        applyUrl: "https://www.stpi.in"
    },
    {
        id: "iit-kharagpur-librarian-2026",
        title: "IIT Kharagpur Librarian 2026",
        organization: "IIT Kharagpur",
        category: "Other Government Jobs",
        location: "Kharagpur",
        qualification: "Library Science",
        vacancies: 1,
        posted: "2026-09-04",
        deadline: "2026-09-17",
        salary: "₹ 40,000 - ₹ 1,20,000",
        jobType: "Education",
        applicationMode: "Online",
        description: "IIT Kharagpur Librarian 2026 recruitment.",
        eligibility: "Library Science degree.",
        selection: "Interview.",
        documents: "Educational certificates, birth certificate.",
        process: "Apply online through IIT Kharagpur portal.",
        officialUrl: "https://www.iitkgp.ac.in",
        applyUrl: "https://www.iitkgp.ac.in"
    },
    {
        id: "iit-kharagpur-software-engineer-2026",
        title: "IIT Kharagpur Software Engineer 2026",
        organization: "IIT Kharagpur",
        category: "IT",
        location: "Kharagpur",
        qualification: "B.Tech / MCA",
        vacancies: 7,
        posted: "2026-09-04",
        deadline: "2026-09-17",
        salary: "₹ 35,000 - ₹ 1,00,000",
        jobType: "IT",
        applicationMode: "Online",
        description: "IIT Kharagpur Software Engineer 2026 recruitment.",
        eligibility: "B.Tech/MCA in Computer Science.",
        selection: "Written test and interview.",
        documents: "Educational certificates, birth certificate.",
        process: "Apply online through IIT Kharagpur portal.",
        officialUrl: "https://www.iitkgp.ac.in",
        applyUrl: "https://www.iitkgp.ac.in"
    },
    {
        id: "csir-cmeri-fitter-2026",
        title: "CSIR CMERI Fitter 2026",
        organization: "CSIR CMERI",
        category: "Technical",
        location: "Durgapur",
        qualification: "ITI",
        vacancies: 27,
        posted: "2026-09-04",
        deadline: "2026-09-13",
        salary: "₹ 20,000 - ₹ 65,000",
        jobType: "Technical",
        applicationMode: "Online",
        description: "CSIR CMERI Fitter 2026 recruitment.",
        eligibility: "ITI in Fitter trade.",
        selection: "Written test and interview.",
        documents: "ITI certificate, birth certificate.",
        process: "Apply online through CSIR CMERI portal.",
        officialUrl: "https://www.cmeri.res.in",
        applyUrl: "https://www.cmeri.res.in"
    },
    {
        id: "csir-cmeri-electrician-2026",
        title: "CSIR CMERI Electrician 2026",
        organization: "CSIR CMERI",
        category: "Technical",
        location: "Durgapur",
        qualification: "ITI",
        vacancies: 15,
        posted: "2026-09-05",
        deadline: "2026-09-15",
        salary: "₹ 20,000 - ₹ 65,000",
        jobType: "Technical",
        applicationMode: "Online",
        description: "CSIR CMERI Electrician 2026 recruitment.",
        eligibility: "ITI in Electrician trade.",
        selection: "Written test and interview.",
        documents: "ITI certificate, birth certificate.",
        process: "Apply online through CSIR CMERI portal.",
        officialUrl: "https://www.cmeri.res.in",
        applyUrl: "https://www.cmeri.res.in"
    },
    {
        id: "tiss-assistant-professor-2026",
        title: "TISS Assistant Professor 2026",
        organization: "Tata Institute of Social Sciences",
        category: "Teaching",
        location: "All India",
        qualification: "PhD",
        vacancies: 1,
        posted: "2026-09-04",
        deadline: "2026-09-16",
        salary: "₹ 40,000 - ₹ 1,20,000",
        jobType: "Teaching",
        applicationMode: "Online",
        description: "TISS Assistant Professor 2026 recruitment.",
        eligibility: "PhD in relevant field.",
        selection: "Interview.",
        documents: "PhD certificate, CV.",
        process: "Apply online through TISS portal.",
        officialUrl: "https://www.tiss.ac.in",
        applyUrl: "https://www.tiss.ac.in"
    },
    {
        id: "nabcons-project-assistant-2026",
        title: "NABCONS Project Assistant 2026",
        organization: "NABCONS",
        category: "Other Government Jobs",
        location: "All India",
        qualification: "Graduate",
        vacancies: 1,
        posted: "2026-09-04",
        deadline: "2026-09-06",
        salary: "As per official notification",
        jobType: "Government-associated Organization",
        applicationMode: "Online",
        description: "NABCONS Project Assistant 2026 recruitment.",
        eligibility: "Graduate degree.",
        selection: "Interview.",
        documents: "Graduate certificate, CV.",
        process: "Apply online through NABCONS portal.",
        officialUrl: "https://www.nabcons.com",
        applyUrl: "https://www.nabcons.com"
    }
];

// ============================================================
// EXPORT FOR USE IN OTHER FILES
// ============================================================
if (typeof module !== 'undefined' && module.exports) {
    module.exports = JOBS;
}
